baseurl = "/"
languageCode = "en_US"
title = "Gabe Kangas"
theme = "HugoMDL"

[permalinks]
    blog = "/blog/:year/:month/:title/"
    pages = "/:title/"

[params]
  author = "Gabe Kangas"
  avatar = "/images/avatar.png"
  background = "/images/background.png"
  description = "Gabe's digital life" #meta description
  image = "/images/avatar-192x210.png" #for frontpage profile card
  mdlPrimary = "gray"
  mdlSecondary = "gray"
  cardtitlecolor = "green"
  cardbackground = "green"
  website = "gabekangas.com"
  email = "gabek@real-ity.com"
#   twitter = "https://twitter.com/firstname_lastname"
  github = "https://github.com/gabek/"
  linkedin = "https://www.linkedin.com/in/gabek/"
#   facebook = "https://facebook.com/firstname_lastname/"
  copyrightyear = "2019"
  frontpageposts = 6 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "Junk"
  url = "/junk/"
  weight = -150
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
