baseurl = "https://gabekangas.com"
languageCode = "en_US"
title = "Gabe Kangas"
theme = "HugoMDL"

[outputs]
  page = ["HTML", "Gopher"]
  section = ["HTML", "Gopher"]
  home = ["HTML", "Gopher", "RSS"]

[mediaTypes]
[mediaTypes."text/gopher"]
suffixes = ["txt"]

[outputFormats]
  [outputFormats.Gopher]
    baseName = "post"
    isPlainText = true
    isHTML = false
    mediaType = "text/gopher"
    path = "gopher"
    suffix = "txt"

[permalinks]
    blog = "/blog/:year/:month/:title/"
    pages = "/:title/"

[params]
  author = "Gabe Kangas"
  avatar = "/images/avatar.png"
  background = "/images/background.png"
  description = "Gabe's home page." #meta description
  image = "/images/avatar.png" #for frontpage profile card
  mdlPrimary = "gray"
  mdlSecondary = "gray"
  cardtitlecolor = "green"
  cardbackground = "green"
  website = "gabekangas.com"
  email = "gabek@real-ity.com"
#   twitter = "https://twitter.com/firstname_lastname"
  github = "https://github.com/gabek/"
  linkedin = "https://www.linkedin.com/in/gabek/"
#   facebook = "https://facebook.com/firstname_lastname/"
  copyrightyear = "2019"
  frontpageposts = 10 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"

[related]
threshold = 90
includeNewer = true
toLower = true

[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"